Add rmarkdown to Suggests
Experienced the following in winbuild

* checking re-building of vignette outputs ... [1s] WARNING
Error(s) in re-building vignettes:
--- re-building 'introduction.Rmd' using rmarkdown
Warning in engine$weave(file, quiet = quiet, encoding = enc) :
  The vignette engine knitr::rmarkdown is not available, because the rmarkdown package is not installed. Please install it.
  Error: processing vignette 'introduction.Rmd' failed with diagnostics:
  The 'markdown' package should be declared as a dependency of the 'tableone' package (e.g., in the  'Suggests' field of DESCRIPTION), because it contains vignette(s) built with the 'markdown' package. Please see https://github.com/yihui/knitr/issues/1864 for more information.
  --- failed re-building 'introduction.Rmd'

--- re-building 'smd.Rmd' using rmarkdown
Warning in engine$weave(file, quiet = quiet, encoding = enc) :
  The vignette engine knitr::rmarkdown is not available, because the rmarkdown package is not installed. Please install it.
  Error: processing vignette 'smd.Rmd' failed with diagnostics:
  The 'markdown' package should be declared as a dependency of the 'tableone' package (e.g., in the  'Suggests' field of DESCRIPTION), because it contains vignette(s) built with the 'markdown' package. Please see https://github.com/yihui/knitr/issues/1864 for more information.
  --- failed re-building 'smd.Rmd'

SUMMARY: processing the following files failed:
  'introduction.Rmd' 'smd.Rmd'

Error: Vignette re-building failed.